GET http://127.0.0.1:4002/shopping

###
POST https://61yyamun1i.execute-api.us-east-1.amazonaws.com/dev/shopping
Content-Type: application/json 

{
    "membershipPlan": "Bronze",
    "value": 10,
    "status": "APPROVED",
    "buyer": {
        "name": "Sebastian Herrera",
        "nid": "987654321",
        "email": "sebastian.herrera@email.com"
    }
}

###
POST http://127.0.0.1:4002/shopping
Content-Type: application/json 

{
    "membershipPlan": "Bronze",
    "value": 10,
    "status": "APPROVED",
    "buyer": {
        "name": "Sebastian Herrera",
        "nid": "987654321",
        "email": "sebastian.herrera@email.com"
    }
}